### ISSUE TITLE
EnableSketchMode vs SketchModeEnable

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-api#130]
we should figure out how to combine these such that we don't break all app users at the same time.

original issue was here: https://github.com/KittyCAD/engine/issues/1774

anyways I think since this is mostly related to here but will need implementation in the engine opening here

**Comment by jessfraz** [comment]
@lf94 if we delete SketchModeEnable will that mess up any of your stuff?

**Comment by lf94** [comment]
Nope, cookie-cutter only uses enable_sketch_mode
