### ISSUE TITLE
batch is_safe_to_batch logic is bad

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-api#273]
this should just auto include anything with a empty response https://github.com/KittyCAD/modeling-api/blob/2e1b19a2a42f6b7c3a2824b65f0dacd1196819fe/modeling-cmds/src/def_enum.rs#L971

**Comment by jessfraz** [comment]
if we get it to autopopulate those with empty responses we could use this in the modeling app versus this hardcoded shit https://github.com/KittyCAD/modeling-app/pull/1871/files#diff-5f06b28afb57092ba5305159f4fbf8e1bf2bf9f77040635a03141e5690893034R99

otherwise we should just delete this function as it is dead code and no longer used anuywhere

cc @lf94

**Comment by adamchalmers** [comment]
Done
